# Generated by Django 5.0.1 on 2024-01-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_area_name_alter_producttype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='fax',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='tel',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
