# Generated by Django 4.2.6 on 2024-01-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_inputinvoice_invoice_no_alter_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputinvoice',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
