# Generated by Django 4.2.6 on 2024-01-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_inputinvoicecounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputinvoicecounter',
            name='no',
            field=models.IntegerField(default=1),
        ),
    ]
