# Generated by Django 4.2.6 on 2024-01-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_inputinvoicecounter_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputinvoicecounter',
            name='on_date',
            field=models.CharField(max_length=8),
        ),
    ]
