# Generated by Django 4.2.6 on 2024-01-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_inputinvoicecounter_on_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='inputinvoice',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
