# Generated by Django 4.2.6 on 2024-01-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_inputinvoice_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producttype',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
