# Generated by Django 4.2.6 on 2024-01-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productcategory_count_producttype_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
