# Generated by Django 4.2.6 on 2024-01-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_area_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
