# Generated by Django 5.0.1 on 2024-01-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_area_count_alter_productcategory_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputinvoice',
            name='type',
            field=models.IntegerField(choices=[(1, 'create'), (2, 'update')], default=1),
        ),
    ]
