# Generated by Django 5.0.1 on 2024-01-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_inputinvoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='zip',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='inputinvoice',
            name='type',
            field=models.IntegerField(choices=[(1, 'new'), (2, 'add')], default=1),
        ),
    ]
